### ISSUE TITLE
CAN extended only sending standard ID

### ISSUE THREAD

**Issue by EVenthusiest** [pierremolinaro/acan2515#14]
Great library you have here and incredibly well documented. I have two devices CAN lines connected to each other sending data back and forth. The chip with the ACAN library can receive CAN packets no problem but when it transmits packets extended ID's become standard ID's.  This is not a problem with receiving so I am a little stumped what could be the issue. I have attached my code of transmitting below. Thank you so much for your help.

                can1.poll();

		CAN1_Transmit_Frame.rtr = false;
		CAN1_Transmit_Frame.ext == true;
		CAN1_Transmit_Frame.id = 0x180238f1;
		CAN1_Transmit_Frame.len = 8;
		//CAN1_Transmit_Frame.id;

		CAN1_Transmit_Frame.data64 = mcu_power_control.controller_out;
	
		Serial.print(CAN1_Transmit_Frame.id,HEX);
		Serial.println(",");

		bool can_attempt = can1.tryToSend(CAN1_Transmit_Frame);
		if (can_attempt)
		{
			Serial.print("packet_sent");
		}

**Comment by pierremolinaro** [comment]
Thank you very much for your message.

I think the problem in your code is the following line:
> 	CAN1_Transmit_Frame.ext == true;
It does not perform an assignment, but a comparison. Unfortunatly the Arduino's C++ compiler settings do not detect this.
Best regards,
Pierre
