### ISSUE TITLE
Please confirm if this library is compatible with Arduino Nano 33 BLE and Arduino Nano 33 BLE Sense

### ISSUE THREAD

**Issue by arpita-agrawal** [pierremolinaro/acan2515#22]
Please confirm if this library is compatible with Arduino Nano 33 BLE and Arduino Nano 33 BLE Sense

**Comment by pierremolinaro** [comment]
Hello,

I have never used theses boards, however as they provide SPI interface (SCK, MOSI and MISO), I think it is ok.

Best regards,

Pierre

**Comment by arpita-agrawal** [comment]
Hi Pierre,

I tried to use the loopback sketch with Nano33BLE Sense while connecting
 SeedStudio CAN Shield to it. Please note that this shield is working well with the Arduino Uno. 

I am getting a configuration error 0x1:

![CAN](https://user-images.githubusercontent.com/37394082/98928737-27081180-2500-11eb-901d-ce9505be7921.jpg)

**Comment by pierremolinaro** [comment]
Hi,

Error 0x1 means the driver cannot talk with the MCP2515. Please check hardware connection, MCP2515 frequency, and check the MCP2515 power is 3.3 V.

Can you tell me the connections you have done ?

Pierre

**Comment by arpita-agrawal** [comment]
Hi Pierre,

Here are the connections that were made. The MCP2515 power was 3.3 V. We used the default freq from the loopback demo sketch.
![CAN connection](https://user-images.githubusercontent.com/37394082/100326340-d6a8ad80-2fef-11eb-9592-6acb3bdad86c.png)

Let me know if I can help with more information.

Thanks
Arpita

**Comment by pierremolinaro** [comment]
Hello Arpita,

Thank for the schematic, I will include it in the documentation of the next release of the library.

Best regards,

Pierre
