### ISSUE TITLE
Can not receive EXT CAN 

### ISSUE THREAD

**Issue by ngochoangimsat** [pierremolinaro/acan2515#24]
Can you check why This code can print standard can id but not ext can id.  If I receive 11 bit ID then it can receive ok but if i receive  29 bit id then the loop function never print anything. Note that in my BUS have 11 bit ID and 29Bit ID too
`
#include <ACAN2515.h>
CANMessage canMsg_rx;
static const byte MCP2515_CS1 = 10 ; // CS input of MCP2515 CAN1
static const byte MCP2515_INT1 = 2 ; // INT output of MCP2515 CAN1
ACAN2515 CAN1(MCP2515_CS1, SPI, MCP2515_INT1);
static const uint32_t QUARTZ_FREQUENCY = 16UL * 1000UL * 1000UL; // 16 MHz
void setup() {
  Serial.begin (115200) ;
  while (!Serial) {
    delay (50) ;
  }
  SPI.begin();
  ACAN2515Settings settings (QUARTZ_FREQUENCY, 500 * 1000UL);
  settings.mTransmitBuffer0Size = 5 ;
  settings.mTransmitBuffer1Size = 0 ;
  settings.mTransmitBuffer2Size = 0 ;
  settings.mReceiveBufferSize = 5 ;
  settings.mRequestedMode = ACAN2515Settings::NormalMode;
  const uint16_t errorCode1 = CAN.begin(settings, [] {CAN.isr();});
  if (errorCode1 != 0) {
    Serial.print ("Configuration CAN error 0x") ;
    Serial.println (errorCode1, HEX) ;
  } else {
    Serial.println ("Configuration CAN OK!") ;
  }
}

void loop() {
  if (CAN.receive(canMsg_rx)) {
    Serial.println(canMsg_rx.id, HEX);
  }
}

`

**Comment by pierremolinaro** [comment]
Hello,

If you use an Arduino Uno, I think the bug comes from this line:
canMsg_tx.id <http://canmsg_tx.id/> = 0x123456;

For an Arduino Uno, the int is a 16-bit signed integer, so 0x123456 is 0x3456.

Just add the UL suffix:
canMsg_tx.id <http://canmsg_tx.id/> = 0x123456UL;

Best Regard,

Pierre

**Comment by ngochoangimsat** [comment]
the problem is receive message, not the transmit .
I can receive 29 bit id only with extend filter. 
Without extend filter we can only receive 11 bit ID

**Comment by pierremolinaro** [comment]
What is your platform ? Did you try in loopback mode ?
