### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by hicksan** [pierremolinaro/acan2515#30]
Can this library work with an ESP8266, please?

**Comment by pierremolinaro** [comment]
The library as it is does not compile for ESP8266. I think that changing the #ifdef ARDUINO_ARCH_ESP32 to #ifdef ARDUINO_ARCH_ESP8266 should satisfy the compilation, but it does not guarantee that the library will run correctly.
Unfortunately, I don't have an ESP8266 card, so I can't do a test.
