### ISSUE TITLE
ACAN2515Settings::mRolloverEnable - mismatch between code and documentation

### ISSUE THREAD

**Issue by PatrykSSS** [pierremolinaro/acan2515#5]
It is false by default in the documentation:
9.1 Default behaviour
You can set the mRolloverEnable property of your ACAN2515Settings object to true (it is false by
default).

Yet set to true in ACAN2515Settings{} definition (which I prefer BTW):
public : bool mRolloverEnable = true ;

**Comment by pierremolinaro** [comment]
You are right, I will update the documentation and I draft a new release.

Best Regards,

Pierre
